services:
  php:
    env_file: .env
    build: ./docker
    container_name: "calliopen-php-{{BRANCH_NAME}}"
    environment:
      SERVER_NAME: ":80"
    volumes:
      - .:/app
    depends_on:
      - localmysql
    labels:
      caddy: "{{DOMAIN}}"
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - web
      - sql

  localmysql:
    image: mysql:8.4
    container_name: "calliopen-mysql-{{BRANCH_NAME}}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "{{DB_PASSWORD}}"
      MYSQL_DATABASE: calliopen
      MYSQL_USER: calliopen
      MYSQL_PASSWORD: "{{DB_PASSWORD}}"
    volumes:
      - "{{DATABASE_PERSIST_PATH}}:/var/lib/mysql"
    networks:
      - sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "calliopen-pma-{{BRANCH_NAME}}"
    restart: always
    environment:
      PMA_HOST: localmysql
    depends_on:
      - localmysql
    labels:
      caddy: "{{PMA_DOMAIN}}"
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - web
      - sql

networks:
  web:
    name: web
    external: true
  sql: