services:
  php:
    build: ./docker
    container_name: calliopen-php
    environment:
      SERVER_NAME: ":80"
    volumes:
      - .:/app
    ports:
      - "9912:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    container_name: calliopen-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calliopen
      MYSQL_USER: calliopen
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: calliopen-pma
    restart: always
    ports:
      - "9913:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: calliopen
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local