name: Deploy App

on:
  push:
    branches:
      - main
      - "**"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  call-deploy:
    uses: tonsoo/deployer/.github/workflows/deploy.laravel.yml@main
    secrets:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
    with:
      repo: tonsoo/calliopen-backend
      domain: calliopen.com.br
      sub-domain: dev # Your dev branches will be accessible at branch.dev.example.com
      add-to-deploys: true # Will create an entry in your deploys lists
      app-name: calliopen
